services:
  workspace:
    build:
      context: ..
      dockerfile: infrastructure/docker/workspace.Dockerfile
    volumes:
      - ..:/workspaces/Szczypior-Discord-Bot:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspaces/Szczypior-Discord-Bot
    command: sleep infinity
    env_file:
      - ../.env
    environment:
      DB_SERVICE_BASE_URL: http://db-service:80
    dns:
      - 127.0.0.11
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - szczypior-network

  db-service:
    build:
      context: ..
      dockerfile: infrastructure/docker/db-service.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../services/db-service:/app/db-service:cached
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8080:80"
    networks:
      - szczypior-network
    profiles: [ "api" ]

  discord-bot:
    build:
      context: ..
      dockerfile: infrastructure/docker/discord-bot.Dockerfile
    env_file:
      - ../.env
    environment:
      API_URL: http://db-service:80
    depends_on:
      - db-service
    networks:
      - szczypior-network
    profiles: [ "bot" ]
  web-dashboard:
    # NOWY SERWIS DJANGO+REACT
    build:
      context: ..
      dockerfile: infrastructure/docker/web-dashboard.Dockerfile # Twój Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../services/web-dashboard:/app/web-dashboard:cached
    ports:
      - "8001:8001"
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8001"
    networks:
      - szczypior-network
    profiles: [ "dashboard" ] # osobny profil

  web-frontend:
    build:
      context: ..
      dockerfile: infrastructure/docker/web-frontend.Dockerfile
    ports:
      - "8002:80"
    networks:
      - szczypior-network
    profiles: [ "frontend" ]

networks:
  szczypior-network:
    external: true
    name: szczypior-dev
