"""Shared constants copied from discord-bot domain model."""

ACTIVITY_TYPES = {
    "bieganie_teren": {
        "emoji": "🏃",
        "base_points": 1000,
        "unit": "km",
        "min_distance": 0,
        "bonuses": ["obciążenie", "przewyższenie"],
        "display_name": "Bieganie (Teren)",
    },
    "bieganie_bieznia": {
        "emoji": "🏃‍♂️",
        "base_points": 800,
        "unit": "km",
        "min_distance": 0,
        "bonuses": ["obciążenie"],
        "display_name": "Bieganie (Bieżnia)",
    },
    "plywanie": {
        "emoji": "🏊",
        "base_points": 4000,
        "unit": "km",
        "min_distance": 0,
        "bonuses": [],
        "display_name": "Pływanie",
    },
    "rower": {
        "emoji": "🚴",
        "base_points": 300,
        "unit": "km",
        "min_distance": 6,
        "bonuses": ["przewyższenie"],
        "display_name": "Rower/Rolki",
    },
    "spacer": {
        "emoji": "🚶",
        "base_points": 200,
        "unit": "km",
        "min_distance": 3,
        "bonuses": ["obciążenie", "przewyższenie"],
        "display_name": "Spacer/Trekking",
    },
    "cardio": {
        "emoji": "🔫",
        "base_points": 800,
        "unit": "km",
        "min_distance": 0,
        "bonuses": ["obciążenie", "przewyższenie"],
        "display_name": "Inne Cardio (wioślarz, orbitrek, ASG)",
    },
}


ACTIVITY_KEYWORDS = {
    "bieganie_teren": [
      "bieg",
      "biegu",
      "bieganie",
      "bieganiu",
      "biegałem",
      "biegałam",
      "biegł",
      "biegła",
      "running",
      "run",
      "ran",
      "jogging",
      "jog",
      "trail",
      "trailrunning",
      "trail running",
      "teren",
      "terenowy",
      "terenowe",
      "terenówka",
      "biegnąłem",
      "biegnąłam",
      "biegną",
      "pobiegać",
      "pobiegałem",
      "pobiegałam"
    ],
    "bieganie_bieznia": [
      "bieżnia",
      "bieżni",
      "bieznia",
      "biezni",
      "bieżnią",
      "bieznią",
      "treadmill",
      "indoor running",
      "indoor run"
    ],
    "plywanie": [
      "pływanie",
      "pływaniu",
      "pływał",
      "pływała",
      "pływałem",
      "pływałam",
      "plywanie",
      "plywaniu",
      "plywal",
      "plywala",
      "plywalem",
      "plywalam",
      "swimming",
      "swim",
      "swam",
      "pool",
      "basen",
      "basenie",
      "basenu",
      "open water",
      "openwater",
      "zalew",
      "jezioro",
      "morze"
    ],
    "rower": [
      "rower",
      "roweru",
      "rowerem",
      "rowerze",
      "rowerowy",
      "rowerowa",
      "cycling",
      "cycle",
      "bike",
      "biking",
      "bicycle",
      "rolki",
      "rolkach",
      "rolkami",
      "roller",
      "skating",
      "inline"
    ],
    "spacer": [
      "spacer",
      "spaceru",
      "spacerem",
      "spacerze",
      "spacerowanie",
      "spacerował",
      "walking",
      "walk",
      "walked",
      "chodzenie",
      "chodzeniu",
      "chodził",
      "chodziła",
      "hiking",
      "hike",
      "hiked",
      "trekking",
      "trek",
      "marsz",
      "marszobieg",
      "nordic walking",
      "kije"
    ],
    "cardio": [
      "cardio",
      "kardio",
      "siłownia",
      "silownia",
      "gym",
      "fitness",
      "rowing",
      "wioślarz",
      "wioslarz",
      "rower stacjonarny",
      "elliptical",
      "orbitrek",
      "eliptyczny",
      "soccer",
      "football",
      "piłka",
      "pilka",
      "nożna",
      "nozna",
      "crossfit",
      "cross fit",
      "trening",
      "workout",
      "ćwiczenia",
      "cwiczenia",
      "aerobik",
      "zumba",
      "spinning",
      "step",
      "boks",
      "walka"
    ]
  },


POINTS_BONUSES = {
    "weight_bonus": {
      "min_weight_kg": 5,
      "distance_points_multiplier": 1.5
                     },
    "elevation_bonus": {
      "meters_step": 50,
      "points_per_step": 500
    }
}